### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by mounimk** [thomasneff/YGOLOTDPatchDraft#1]
Hi, i am embarrassed to ask this, but how do i start the program, i downloaded the code as Zip, then extracted the files to a new folder, but there's no **.exe** file to start the program. excuse my poor knowledge :)

**Comment by mounimk** [comment]
never mind, i am new to github i should have downloaded the release, thank you

**Comment by Arefu** [comment]
You would normally have to compile it with Visual Studio or any other C# compiler.
