### ISSUE TITLE
New Game and hope for an update =)

### ISSUE THREAD

**Issue by EyderSnob** [thomasneff/YGOLOTDPatchDraft#3]
Hey there, because i don't know how to contact you i'll post it here. 

There was a new version of the game released. I have been using your tool every single time playing lotd, so i wanted to ask what the chances are that this tool gets updated?

The other modding guys got active again in the discord of Arefu / Wolf.

Greets

**Comment by thomasneff** [comment]
What a coincidence - just today I was thinking about this tool and the possibility of checking it out for the new game.

I'll give it a shot in the next couple of days and see if and how things have changed between the old game and the new game. At the very least I'll need to figure out which cards are in the game and update the internal card database for the new game such that new cards can appear in the draft as well. 

Depending on how the new game works, this might take a while, but I'll update here once I've done an initial investigation. 

It's awesome that you used the tool often, that's nice to hear :)

**Comment by EyderSnob** [comment]
Realy good sign to get a such a quick response =)

I wish you the best of luck and look forward to the next post of yours.

Ps: Your tool was a great way to keep the game refreshing

**Comment by thomasneff** [comment]
I updated the tool in a separate branch and added a new release specifically for this version. 

It can be found in https://github.com/thomasneff/YGOLOTDPatchDraft/releases/tag/LinkEvo_1.0

There shouldn't be any obvious bugs and I tested it with various settings for the draft packs and the AI draft decks. Let me know if there are any issues.
